DROP TABLE MEMBERBOARD;
DROP SEQUENCE MEMBERBOARDSEQ;

CREATE SEQUENCE MEMBERBOARDSEQ;
-- 회원번호, 아이디, 비밀번호, 이름, 주소, 전화번호, 이메일, 가입여부(Y/N), 등급(ADMIN/USER/...)
CREATE TABLE MEMBERBOARD(
	MYNO NUMBER NOT NULL,
	MYID VARCHAR2(500) NOT NULL,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,
	MYEMAIL VARCHAR2(100) NOT NULL,
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(100) NOT NULL,
	CONSTRAINT MYMEMBER_PK PRIMARY KEY (MYNO),
	CONSTRAINT MYMEMBER_UK_ID UNIQUE (MYID),
	CONSTRAINT MYMEMBER_UK_PHONE UNIQUE (MYPHONE),
	CONSTRAINT MYMEMBER_UK_EMAIL UNIQUE (MYEMAIL),
	CONSTRAINT MYMEMBER_CK_MYENABLED CHECK (MYENABLED IN ('Y','N'))
);

INSERT INTO MEMBERBOARD VALUES (MEMBERBOARDSEQ.NEXTVAL, '관리자', '1234', '이태식', '인천시', '0101111111',
'dlxotlr99@naver.com', 'Y', 'ADMIN');

INSERT INTO MEMBERBOARD VALUES (MEMBERBOARDSEQ.NEXTVAL, 'test', 'test', '쩝쩝이', '서울', '0102222222',
'user1@user.com', 'Y', 'USER');

SELECT * FROM MEMBERBOARD;

UPDATE MEMBERBOARD SET MYNAME='바나나' WHERE MYID='test';

UPDATE MEMBERBOARD SET MYENABLED='Y' WHERE MYID='test';

















