DROP SEQUENCE MEMBERNOSEQ;
DROP TABLE MEMBERBOARD;

CREATE SEQUENCE MEMBERNOSEQ;
CREATE TABLE MEMBERBOARD (
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(500) NOT NULL,
	MEMBERPW VARCHAR2(500) NOT NULL,
	MEMBERNAME VARCHAR2(10) NOT NULL,
	MEMBERPHONE VARCHAR2(30) NOT NULL,
	MEMBERROLE VARCHAR2(10) NOT NULL,
	MEMBERENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT MEMBERBOARD_MEMBERID_UQ UNIQUE (MEMBERID),
	CONSTRAINT MEMBERBOARD_MEMBERPHONE_UQ UNIQUE (MEMBERPHONE),
	CONSTRAINT MEMBERBOARD_MEMBERROLE_CHK CHECK (MEMBERROLE IN ('ADMIN','USER')),
	CONSTRAINT MEMBERBOARD_MEMBERENABLED_CHK CHECK (MEMBERENABLED IN ('Y','N'))
);

INSERT INTO MEMBERBOARD VALUES (MEMBERNOSEQ.NEXTVAL, '관리자', 1234, '이태식', '0101111111', 'ADMIN','Y');

INSERT INTO MEMBERBOARD VALUES (MEMBERNOSEQ.NEXTVAL, '유저1', 1234, '사람1', '0102222222', 'USER','Y');
INSERT INTO MEMBERBOARD VALUES (MEMBERNOSEQ.NEXTVAL, '유저2', 1234, '사람2', '0103333333', 'USER','Y');
INSERT INTO MEMBERBOARD VALUES (MEMBERNOSEQ.NEXTVAL, '유저3', 1234, '사람3', '0104444444', 'USER','Y');

UPDATE MEMBERBOARD SET MEMBERENABLED='Y' WHERE MEMBERID='유저1';

SELECT * FROM MEMBERBOARD;