DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

-- 글 번호 +1 SEQUENCE
CREATE SEQUENCE BOARDNOSEQ;
-- 그룹번호 +1 SEQUENCE
CREATE SEQUENCE GROUPNOSEQ;
-- 글번호, 그룹번호, 그룹순서, 제목탭, 삭제여부
-- 제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERBOARD (
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,&boardno=${dto.boardno}
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT ANSWER_DELFLAG_CHK CHECK (DELFLAG IN ('Y','N')) -- Y:삭제됨 N:살아있음
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'N','1번 글', '1번 내용', '유저1', SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'1번글','1번내용','1번',SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'2번글','2번내용','2번',SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'3번글','3번내용','3번',SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'4번글','4번내용','4번',SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'5번글','5번내용','5번',SYSDATE);

-- ----------------------------------------------------------------------------------- --
SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
'RE:5번','5번 답변 내용','유저1',SYSDATE);

UPDATE ANSWERBOARD
SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5)
      AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
'RE:5번','5번 답변 내용','유저2',SYSDATE);

UPDATE ANSWERBOARD
SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5)
      AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7);
      
INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
'RE:RE:5번','5번 답변 내용','유저2',SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

UPDATE ANSWERBOARD SET WRITER='유저3' WHERE GROUPNO=5 AND GROUPSQ=3;
-- ------------------------------------------------------------------------- --
INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=4)+1,
'RE:4번','4번 답변 내용','유저1',SYSDATE);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=9)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=9)+1,
'RE:RE:4번','4번 답변 내용','유저2',SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

UPDATE ANSWERBOARD
SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4)
      AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=4)+1,
'RE:4번','4번 답변 내용','유저3',SYSDATE);

UPDATE ANSWERBOARD
SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4)
      AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11);

INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=11)+1,
'RE:RE:4번','4번 답변 내용','유저4',SYSDATE);

-- ? : 부모의 글번호
UPDATE ANSWERBOARD
SET GROUPSQ=GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4)
      AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11);
-- ? : 부모의 글 번호
INSERT INTO ANSWERBOARD
VALUES (BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=11)+1,
'RE:RE:4번','4번 답변 내용','유저4',SYSDATE);
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

      
      
      
      
      
      
      
      
      
      
















